apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-eqtg
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0011-tenant/tkrw-pr712-0075-0011-app/devfile-sample-eqtg@sha256:e1e9ae21ecd4b02c5ee4d35f196a82352c511c867471ee3ce355bf388e9dd1bc
        name: my-nodejs
        resources: {}
status: {}
